<a href="https://colab.research.google.com/github/11deybishal-commits/ML-models/blob/main/credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [4]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
277210,167518.0,-0.250465,0.932919,0.392284,-0.505438,0.472820,-0.687210,0.978017,-0.260425,0.084702,...,-0.258948,-0.405009,0.055662,0.002694,-0.628533,0.160021,0.077710,-0.041144,3.99,0.0
277211,167518.0,1.909690,-0.206280,-1.001002,1.050869,0.242225,0.318109,-0.235292,0.096941,0.479922,...,0.076915,0.239160,0.087737,0.167680,0.042727,-0.680737,0.018405,-0.039718,45.00,0.0
277212,167519.0,-1.281795,-0.262064,0.264716,-2.911065,-0.968937,-0.478164,-0.917177,0.795292,-2.601073,...,0.088970,0.300705,-0.163235,-0.388332,-0.129704,-0.279411,-0.219501,-0.072573,22.00,0.0
277213,167520.0,1.585981,-0.215269,-3.350544,0.477325,1.429973,0.165988,0.426513,0.133443,0.092177,...,0.066533,-0.030211,-0.125912,-1.869211,-0.172846,0.792241,-0.059048,0.000872,190.00,0.0
277214,167521.0,2.025306,-0.484690,-0.567508,0.327017,-0.462387,-0.056687,-0.705461,0.064733,1.319235,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277215 entries, 0 to 277214
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    277215 non-null  float64
 1   V1      277215 non-null  float64
 2   V2      277215 non-null  float64
 3   V3      277215 non-null  float64
 4   V4      277215 non-null  float64
 5   V5      277215 non-null  float64
 6   V6      277215 non-null  float64
 7   V7      277215 non-null  float64
 8   V8      277215 non-null  float64
 9   V9      277215 non-null  float64
 10  V10     277215 non-null  float64
 11  V11     277215 non-null  float64
 12  V12     277215 non-null  float64
 13  V13     277215 non-null  float64
 14  V14     277215 non-null  float64
 15  V15     277215 non-null  float64
 16  V16     277215 non-null  float64
 17  V17     277215 non-null  float64
 18  V18     277215 non-null  float64
 19  V19     277214 non-null  float64
 20  V20     277214 non-null  float64
 21  V21     277214 non-null  float64
 22  V22     277214 non-null  float64
 23  V23     277214 non-null  float64
 24  V24     277214 non-null  float64
 25  V25     277214 non-null  float64
 26  V26     277214 non-null  float64
 27  V27     277214 non-null  float64
 28  V28     277214 non-null  float64
 29  Amount  277214 non-null  float64
 30  Class   277214 non-null  float64
dtypes: float64(31)
memory usage: 65.6 MB

In [7]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [8]:
 #distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    276727
1.0       487
Name: count, dtype: int64

In [9]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(276727, 31)
(487, 31)

In [11]:
# statistical measures of the data
legit.Amount.describe()

count    276727.000000
mean         88.894069
std         251.084883
min           0.000000
25%           5.810000
50%          22.340000
75%          78.000000
max       25691.160000
Name: Amount, dtype: float64

In [13]:
#compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,92778.144236,0.005931,-0.015436,0.034065,-0.003859,-0.002894,0.006108,0.006516,-0.001708,0.004670,...,-0.000227,-0.001441,-0.002343,-0.001081,-0.000042,0.003915,-0.000093,-0.000252,0.000003,88.894069
1.0,79834.240246,-4.816122,3.652183,-7.065000,4.576639,-3.179607,-1.398985,-5.612526,0.570034,-2.597563,...,0.372003,0.716151,0.014237,-0.041043,-0.104202,0.041249,0.047424,0.168312,0.075910,121.913326

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fradulent Transaction: 492

In [14]:
legit_sample = legit.sample(n=492)

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
240860,150783.0,1.953435,-0.641822,-0.007765,0.153650,-0.908640,0.174680,-1.139727,0.336490,1.300733,...,0.062577,0.220437,0.370178,0.755444,-0.653860,0.430651,-0.027463,-0.044620,1.00,0.0
245268,152673.0,-0.563397,-0.201619,1.240356,-3.469101,0.075763,0.608956,-0.250631,0.195891,-2.373312,...,-0.207783,-0.101006,-0.503312,-0.292853,0.820254,-0.112577,0.278400,0.100186,3.70,0.0
212537,138900.0,1.915291,-1.273465,-1.640527,-1.034564,-0.394319,-0.401375,-0.327757,-0.099092,-0.591106,...,0.040646,-0.376352,0.155124,0.309713,-0.263552,-0.469310,-0.078511,-0.039547,162.80,0.0
11552,19907.0,1.420046,-0.604408,0.296286,-0.546177,-0.706352,-0.018893,-0.873696,0.037540,0.870561,...,-0.195000,-0.316190,-0.113491,-0.573152,0.564497,-0.243237,-0.026750,-0.015903,5.00,0.0
78303,57467.0,-0.859827,0.864036,0.557502,-0.114081,1.586221,4.253298,-0.866675,1.649816,-0.042147,...,-0.038447,-0.076526,-0.166593,1.001484,0.189958,-0.293950,0.290277,0.120308,9.99,0.0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
274382,165981.0,-5.766879,-8.402154,0.056543,6.950983,9.880564,-5.773192,-5.748879,0.721743,-1.076274,...,0.880395,-0.130436,2.241471,0.665346,-1.890041,-0.120803,0.073269,0.583799,0.00,1.0
274475,166028.0,-0.956390,2.361594,-3.171195,1.970759,0.474761,-1.902598,-0.055178,0.277831,-1.745854,...,0.473211,0.719400,0.122458,-0.255650,-0.619259,-0.484280,0.683535,0.443299,39.90,1.0
275992,166831.0,-2.027135,-1.131890,-1.135194,1.086963,-0.010547,0.423797,3.790880,-1.155595,-0.063434,...,-0.315105,0.575520,0.490842,0.756502,-0.142685,-0.602777,0.508712,-0.091646,634.30,1.0
276071,166883.0,2.091900,-0.757459,-1.192258,-0.755458,-0.620324,-0.322077,-1.082511,0.117200,-0.140927,...,0.288253,0.831939,0.142007,0.592615,-0.196143,-0.136676,0.020182,-0.015470,19.95,1.0
276864,167338.0,-1.374424,2.793185,-4.346572,2.400731,-1.688433,0.111136,-0.922038,-2.149930,-2.027474,...,-0.870779,0.504849,0.137994,0.368275,0.103137,-0.414209,0.454982,0.096711,349.08,1.0

In [18]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    487
Name: count, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,93040.119919,0.014733,0.015457,0.06892,0.013769,-0.018834,0.064395,-0.077397,0.036479,0.003397,...,-0.042027,0.021151,-0.032688,0.014361,0.020106,-0.005575,-0.029918,-0.005010,0.002498,79.606504
1.0,79834.240246,-4.816122,3.652183,-7.06500,4.576639,-3.179607,-1.398985,-5.612526,0.570034,-2.597563,...,0.372003,0.716151,0.014237,-0.041043,-0.104202,0.041249,0.047424,0.168312,0.075910,121.913326

Splitting the data into Features and Targets

In [20]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
240860  150783.0  1.953435 -0.641822 -0.007765  0.153650 -0.908640  0.174680
245268  152673.0 -0.563397 -0.201619  1.240356 -3.469101  0.075763  0.608956
212537  138900.0  1.915291 -1.273465 -1.640527 -1.034564 -0.394319 -0.401375
11552    19907.0  1.420046 -0.604408  0.296286 -0.546177 -0.706352 -0.018893
78303    57467.0 -0.859827  0.864036  0.557502 -0.114081  1.586221  4.253298
...          ...       ...       ...       ...       ...       ...       ...
274382  165981.0 -5.766879 -8.402154  0.056543  6.950983  9.880564 -5.773192
274475  166028.0 -0.956390  2.361594 -3.171195  1.970759  0.474761 -1.902598
275992  166831.0 -2.027135 -1.131890 -1.135194  1.086963 -0.010547  0.423797
276071  166883.0  2.091900 -0.757459 -1.192258 -0.755458 -0.620324 -0.322077
276864  167338.0 -1.374424  2.793185 -4.346572  2.400731 -1.688433  0.111136

              V7        V8        V9  ...       V20       V21       V22  \
240860 -1.139727  0.336490  1.300733  ... -0.234188  0.062577  0.220437
245268 -0.250631  0.195891 -2.373312  ... -0.085663 -0.207783 -0.101006
212537 -0.327757 -0.099092 -0.591106  ...  0.245353  0.040646 -0.376352
11552  -0.873696  0.037540  0.870561  ... -0.067909 -0.195000 -0.316190
78303  -0.866675  1.649816 -0.042147  ...  0.180623 -0.038447 -0.076526
...          ...       ...       ...  ...       ...       ...       ...
274382 -5.748879  0.721743 -1.076274  ...  2.493224  0.880395 -0.130436
274475 -0.055178  0.277831 -1.745854  ...  0.190877  0.473211  0.719400
275992  3.790880 -1.155595 -0.063434  ...  0.033804 -0.315105  0.575520
276071 -1.082511  0.117200 -0.140927  ...  0.037438  0.288253  0.831939
276864 -0.922038 -2.149930 -2.027474  ...  0.650196 -0.870779  0.504849

             V23       V24       V25       V26       V27       V28  Amount
240860  0.370178  0.755444 -0.653860  0.430651 -0.027463 -0.044620    1.00
245268 -0.503312 -0.292853  0.820254 -0.112577  0.278400  0.100186    3.70
212537  0.155124  0.309713 -0.263552 -0.469310 -0.078511 -0.039547  162.80
11552  -0.113491 -0.573152  0.564497 -0.243237 -0.026750 -0.015903    5.00
78303  -0.166593  1.001484  0.189958 -0.293950  0.290277  0.120308    9.99
...          ...       ...       ...       ...       ...       ...     ...
274382  2.241471  0.665346 -1.890041 -0.120803  0.073269  0.583799    0.00
274475  0.122458 -0.255650 -0.619259 -0.484280  0.683535  0.443299   39.90
275992  0.490842  0.756502 -0.142685 -0.602777  0.508712 -0.091646  634.30
276071  0.142007  0.592615 -0.196143 -0.136676  0.020182 -0.015470   19.95
276864  0.137994  0.368275  0.103137 -0.414209  0.454982  0.096711  349.08

[979 rows x 30 columns]

In [22]:
print(Y)

240860    0.0
245268    0.0
212537    0.0
11552     0.0
78303     0.0
         ...
274382    1.0
274475    1.0
275992    1.0
276071    1.0
276864    1.0
Name: Class, Length: 979, dtype: float64

Split data into Training data and Testing Data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(979, 30) (783, 30) (196, 30)

Model Training
Logistic Regression

In [25]:
model = LogisticRegression()

In [26]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation
Accuracy Score

In [28]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [32]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9425287356321839

In [33]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [34]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9336734693877551

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
classifier = RandomForestClassifier(n_estimators = 100)

In [37]:
classifier.fit(X_train, Y_train)

RandomForestClassifier()

In [41]:
# accuracy on training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy_classifier= accuracy_score(X_train_prediction, Y_train)

In [42]:
print('Accuracy score on Training Data : ', training_data_accuracy_classifier)

Accuracy score on Training Data :  1.0

In [43]:
# accuracy on test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy_classifier = accuracy_score(X_test_prediction, Y_test)

In [44]:
print('Accuracy score on Testing Data : ', test_data_accuracy_classifier)

Accuracy score on Testing Data :  0.9132653061224489